import { WhatsappMessageClient } from './services/WHATSAPP-ms/whatsapp-message/whatsapp-message.client';
import { PhoneNumberClient } from './services/WHATSAPP-ms/phone-number/phone-number.client';
import { ContactConfigClient } from './services/WHATSAPP-ms/contact-config/contact-config.client';
import { UserClient } from './services/user/user.client';
import { WidgetConfigClient } from './services/SUPPORT-ms/widget-config/widget-config.client';
import { ToolTraceClient } from './services/SUPPORT-ms/tool-trace/tool-trace.client';
import { ProductClient } from './services/SUPPORT-ms/product/product.client';
import { MessageClient } from './services/SUPPORT-ms/message/message.client';
import { IssueTagClient } from './services/SUPPORT-ms/issue-tag/issue-tag.client';
import { IssueCommentClient } from './services/SUPPORT-ms/issue-comment/issue-comment.client';
import { IssueClient } from './services/SUPPORT-ms/issue/issue.client';
import { FaqClient } from './services/SUPPORT-ms/faq/faq.client';
import { EventClient } from './services/SUPPORT-ms/event/event.client';
import { DomainClient } from './services/SUPPORT-ms/domain/domain.client';
import { CustomToolClient } from './services/SUPPORT-ms/custom-tool/custom-tool.client';
import { ClientClient } from './services/SUPPORT-ms/client/client.client';
import { NotificationClient } from './services/notification/notification.client';
import { ProductStatClient } from './services/LOG-ms/product-stat/product-stat.client';
import { LogClient } from './services/LOG-ms/log/log.client';
import { LlmTrainingDataClient } from './services/LOG-ms/llm-training-data/llm-training-data.client';
import { AdminNotifClient } from './services/LOG-ms/admin-notif/admin-notif.client';
import { EmailClient } from './services/email/email.client';
import { CaptchaClient } from './services/captcha/captcha.client';
import { SpendClient } from './services/BANK-ms/spend/spend.client';
import { ProductVaultClient } from './services/BANK-ms/product-vault/product-vault.client';
import { DepositClient } from './services/BANK-ms/deposit/deposit.client';
import { TokenClient } from './services/AUTH-ms/token/token.client';
import { AccountDeletionClient } from './services/AUTH-ms/account-deletion/account-deletion.client';
import { StaffContactAgentClient } from './services/AI-ms/staff-contact-agent/staff-contact-agent.client';
import { LlmProviderClient } from './services/AI-ms/llm-provider/llm-provider.client';
import { EditorTaskClient } from './services/AI-ms/editor-task/editor-task.client';
import { EditorAgentClient } from './services/AI-ms/editor-agent/editor-agent.client';
import { DigestorClient } from './services/AI-ms/digestor/digestor.client';
import { ChatAgentClient } from './services/AI-ms/chat-agent/chat-agent.client';
import { AgentMessageClient } from './services/AI-ms/agent-message/agent-message.client';
import { SuperClientConfig } from "@eicrud/client";

export class SuperClient {

    constructor(config: SuperClientConfig) {

        // GENERATED START 1
        this.whatsappMessage = new WhatsappMessageClient(config);
        this.phoneNumber = new PhoneNumberClient(config);
        this.contactConfig = new ContactConfigClient(config);
        this.user = new UserClient(config);
        this.widgetConfig = new WidgetConfigClient(config);
        this.toolTrace = new ToolTraceClient(config);
        this.product = new ProductClient(config);
        this.message = new MessageClient(config);
        this.issueTag = new IssueTagClient(config);
        this.issueComment = new IssueCommentClient(config);
        this.issue = new IssueClient(config);
        this.faq = new FaqClient(config);
        this.event = new EventClient(config);
        this.domain = new DomainClient(config);
        this.customTool = new CustomToolClient(config);
        this.client = new ClientClient(config);
        this.notification = new NotificationClient(config);
        this.productStat = new ProductStatClient(config);
        this.log = new LogClient(config);
        this.llmTrainingData = new LlmTrainingDataClient(config);
        this.adminNotif = new AdminNotifClient(config);
        this.email = new EmailClient(config);
        this.captcha = new CaptchaClient(config);
        this.spend = new SpendClient(config);
        this.productVault = new ProductVaultClient(config);
        this.deposit = new DepositClient(config);
        this.token = new TokenClient(config);
        this.accountDeletion = new AccountDeletionClient(config);
        this.staffContactAgent = new StaffContactAgentClient(config);
        this.llmProvider = new LlmProviderClient(config);
        this.editorTask = new EditorTaskClient(config);
        this.editorAgent = new EditorAgentClient(config);
        this.digestor = new DigestorClient(config);
        this.chatAgent = new ChatAgentClient(config);
        this.agentMessage = new AgentMessageClient(config);
    }

    // GENERATED START 2
    whatsappMessage: WhatsappMessageClient;
    phoneNumber: PhoneNumberClient;
    contactConfig: ContactConfigClient;
    user: UserClient;
    widgetConfig: WidgetConfigClient;
    toolTrace: ToolTraceClient;
    product: ProductClient;
    message: MessageClient;
    issueTag: IssueTagClient;
    issueComment: IssueCommentClient;
    issue: IssueClient;
    faq: FaqClient;
    event: EventClient;
    domain: DomainClient;
    customTool: CustomToolClient;
    client: ClientClient;
    notification: NotificationClient;
    productStat: ProductStatClient;
    log: LogClient;
    llmTrainingData: LlmTrainingDataClient;
    adminNotif: AdminNotifClient;
    email: EmailClient;
    captcha: CaptchaClient;
    spend: SpendClient;
    productVault: ProductVaultClient;
    deposit: DepositClient;
    token: TokenClient;
    accountDeletion: AccountDeletionClient;
    staffContactAgent: StaffContactAgentClient;
    llmProvider: LlmProviderClient;
    editorTask: EditorTaskClient;
    editorAgent: EditorAgentClient;
    digestor: DigestorClient;
    chatAgent: ChatAgentClient;
    agentMessage: AgentMessageClient;
}